// <auto-generated />
using System;
using IbhayiPharmacy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IbhayiPharmacy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251007222030_NewTablesAgain")]
    partial class NewTablesAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IbhayiPharmacy.Models.Active_Ingredient", b =>
                {
                    b.Property<int>("Active_IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Active_IngredientID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Active_IngredientID");

                    b.ToTable("Active_Ingredients");

                    b.HasData(
                        new
                        {
                            Active_IngredientID = 1,
                            Name = "Pylorazine"
                        },
                        new
                        {
                            Active_IngredientID = 2,
                            Name = "Vaspril"
                        },
                        new
                        {
                            Active_IngredientID = 3,
                            Name = "Zentropine"
                        },
                        new
                        {
                            Active_IngredientID = 4,
                            Name = "Histarelin"
                        },
                        new
                        {
                            Active_IngredientID = 5,
                            Name = "Lorvexamine"
                        },
                        new
                        {
                            Active_IngredientID = 6,
                            Name = "Aterolazine"
                        },
                        new
                        {
                            Active_IngredientID = 7,
                            Name = "Bronchomid"
                        },
                        new
                        {
                            Active_IngredientID = 8,
                            Name = "Alveclear"
                        },
                        new
                        {
                            Active_IngredientID = 9,
                            Name = "Epidraxol"
                        },
                        new
                        {
                            Active_IngredientID = 10,
                            Name = "Cortizane"
                        },
                        new
                        {
                            Active_IngredientID = 11,
                            Name = "Glycerrol"
                        },
                        new
                        {
                            Active_IngredientID = 12,
                            Name = "Sonnexil"
                        },
                        new
                        {
                            Active_IngredientID = 13,
                            Name = "Calcitrine"
                        },
                        new
                        {
                            Active_IngredientID = 14,
                            Name = "Phospholax"
                        },
                        new
                        {
                            Active_IngredientID = 15,
                            Name = "Virocelin"
                        },
                        new
                        {
                            Active_IngredientID = 16,
                            Name = "Immubrine"
                        },
                        new
                        {
                            Active_IngredientID = 17,
                            Name = "Trosamine"
                        },
                        new
                        {
                            Active_IngredientID = 18,
                            Name = "Velocidine"
                        },
                        new
                        {
                            Active_IngredientID = 19,
                            Name = "Nexorin"
                        },
                        new
                        {
                            Active_IngredientID = 20,
                            Name = "Zyphralex"
                        },
                        new
                        {
                            Active_IngredientID = 21,
                            Name = "Cardionol"
                        },
                        new
                        {
                            Active_IngredientID = 22,
                            Name = "Alveretol"
                        },
                        new
                        {
                            Active_IngredientID = 23,
                            Name = "Xylogran"
                        },
                        new
                        {
                            Active_IngredientID = 24,
                            Name = "Fematrix"
                        },
                        new
                        {
                            Active_IngredientID = 25,
                            Name = "Plastorin"
                        },
                        new
                        {
                            Active_IngredientID = 26,
                            Name = "Seralox"
                        },
                        new
                        {
                            Active_IngredientID = 27,
                            Name = "Quantrel"
                        },
                        new
                        {
                            Active_IngredientID = 28,
                            Name = "Myvetrin"
                        },
                        new
                        {
                            Active_IngredientID = 29,
                            Name = "Draxolene"
                        },
                        new
                        {
                            Active_IngredientID = 30,
                            Name = "Veltraxin"
                        });
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Customer", b =>
                {
                    b.Property<int>("CustormerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustormerID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustormerID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Custormer_Allergy", b =>
                {
                    b.Property<int>("Custormer_AllergyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Custormer_AllergyID"));

                    b.Property<int>("Active_IngredientID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("Custormer_AllergyID");

                    b.HasIndex("Active_IngredientID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Custormer_Allergies");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCouncilRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorID");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorID = 1,
                            ContactNumber = "071 234 5678",
                            Email = "charmaine@example.com",
                            HealthCouncilRegistrationNumber = "976431",
                            Name = "Charmaine",
                            Surname = "Meintjies"
                        },
                        new
                        {
                            DoctorID = 2,
                            ContactNumber = "072 234 5678",
                            Email = "jacob@example.com",
                            HealthCouncilRegistrationNumber = "316497",
                            Name = "Jacob",
                            Surname = "Moloi"
                        },
                        new
                        {
                            DoctorID = 3,
                            ContactNumber = "073 234 5678",
                            Email = "david@gmail.example",
                            HealthCouncilRegistrationNumber = "718293",
                            Name = "David",
                            Surname = "Greeff"
                        },
                        new
                        {
                            DoctorID = 4,
                            ContactNumber = "075 234 5678",
                            Email = "karien@example.com",
                            HealthCouncilRegistrationNumber = "159753",
                            Name = "Karien",
                            Surname = "Momberg"
                        },
                        new
                        {
                            DoctorID = 5,
                            ContactNumber = "076 234 5678",
                            Email = "felicity@example.com",
                            HealthCouncilRegistrationNumber = "951357",
                            Name = "Felicity",
                            Surname = "Daniels"
                        },
                        new
                        {
                            DoctorID = 6,
                            ContactNumber = "078 234 5678",
                            Email = "errol@example.com",
                            HealthCouncilRegistrationNumber = "852456",
                            Name = "Errol",
                            Surname = "Pieterse"
                        },
                        new
                        {
                            DoctorID = 7,
                            ContactNumber = "079 234 5678",
                            Email = "alyce@example.com",
                            HealthCouncilRegistrationNumber = "654852",
                            Name = "Alyce",
                            Surname = "Morapedi"
                        });
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.DosageForm", b =>
                {
                    b.Property<int>("DosageFormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DosageFormID"));

                    b.Property<string>("DosageFormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DosageFormID");

                    b.ToTable("DosageForms");

                    b.HasData(
                        new
                        {
                            DosageFormID = 1,
                            DosageFormName = "Tablet"
                        },
                        new
                        {
                            DosageFormID = 2,
                            DosageFormName = "Capsule"
                        },
                        new
                        {
                            DosageFormID = 3,
                            DosageFormName = "Suspension"
                        },
                        new
                        {
                            DosageFormID = 4,
                            DosageFormName = "Syrup"
                        },
                        new
                        {
                            DosageFormID = 5,
                            DosageFormName = "Lotion"
                        },
                        new
                        {
                            DosageFormID = 6,
                            DosageFormName = "Spray"
                        },
                        new
                        {
                            DosageFormID = 7,
                            DosageFormName = "Gel"
                        },
                        new
                        {
                            DosageFormID = 8,
                            DosageFormName = "Suppository"
                        },
                        new
                        {
                            DosageFormID = 9,
                            DosageFormName = "Injectable"
                        },
                        new
                        {
                            DosageFormID = 10,
                            DosageFormName = "Drops"
                        },
                        new
                        {
                            DosageFormID = 11,
                            DosageFormName = "IV Drip"
                        },
                        new
                        {
                            DosageFormID = 12,
                            DosageFormName = "Powder"
                        });
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Medication", b =>
                {
                    b.Property<int>("MedcationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedcationID"));

                    b.Property<int>("CurrentPrice")
                        .HasColumnType("int");

                    b.Property<int>("DosageFormID")
                        .HasColumnType("int");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("ReOrderLevel")
                        .HasColumnType("int");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("MedcationID");

                    b.HasIndex("DosageFormID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            MedcationID = 1,
                            CurrentPrice = 150,
                            DosageFormID = 1,
                            MedicationName = "CardioVex",
                            QuantityOnHand = 90,
                            ReOrderLevel = 100,
                            Schedule = "6",
                            SupplierID = 1
                        },
                        new
                        {
                            MedcationID = 2,
                            CurrentPrice = 200,
                            DosageFormID = 1,
                            MedicationName = "Neurocalm",
                            QuantityOnHand = 100,
                            ReOrderLevel = 110,
                            Schedule = "2",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 3,
                            CurrentPrice = 180,
                            DosageFormID = 12,
                            MedicationName = "Allerfree Duo",
                            QuantityOnHand = 100,
                            ReOrderLevel = 150,
                            Schedule = "0",
                            SupplierID = 3
                        },
                        new
                        {
                            MedcationID = 4,
                            CurrentPrice = 95,
                            DosageFormID = 1,
                            MedicationName = "GastroEase",
                            QuantityOnHand = 470,
                            ReOrderLevel = 400,
                            Schedule = "3",
                            SupplierID = 4
                        },
                        new
                        {
                            MedcationID = 5,
                            CurrentPrice = 120,
                            DosageFormID = 1,
                            MedicationName = "Respivent",
                            QuantityOnHand = 490,
                            ReOrderLevel = 300,
                            Schedule = "3",
                            SupplierID = 5
                        },
                        new
                        {
                            MedcationID = 6,
                            CurrentPrice = 85,
                            DosageFormID = 1,
                            MedicationName = "Dermagard",
                            QuantityOnHand = 790,
                            ReOrderLevel = 600,
                            Schedule = "3",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 7,
                            CurrentPrice = 210,
                            DosageFormID = 1,
                            MedicationName = "Metaborex",
                            QuantityOnHand = 250,
                            ReOrderLevel = 200,
                            Schedule = "4",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 8,
                            CurrentPrice = 175,
                            DosageFormID = 1,
                            MedicationName = "Sleeptraze",
                            QuantityOnHand = 110,
                            ReOrderLevel = 100,
                            Schedule = "2",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 9,
                            CurrentPrice = 300,
                            DosageFormID = 3,
                            MedicationName = "OsteoFlex",
                            QuantityOnHand = 210,
                            ReOrderLevel = 200,
                            Schedule = "3",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 10,
                            CurrentPrice = 450,
                            DosageFormID = 9,
                            MedicationName = "Immunexin",
                            QuantityOnHand = 190,
                            ReOrderLevel = 200,
                            Schedule = "6",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 11,
                            CurrentPrice = 600,
                            DosageFormID = 11,
                            MedicationName = "CardioPlus",
                            QuantityOnHand = 600,
                            ReOrderLevel = 500,
                            Schedule = "6",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 12,
                            CurrentPrice = 350,
                            DosageFormID = 11,
                            MedicationName = "AllerCalm",
                            QuantityOnHand = 410,
                            ReOrderLevel = 400,
                            Schedule = "6",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 13,
                            CurrentPrice = 280,
                            DosageFormID = 9,
                            MedicationName = "RespirAid",
                            QuantityOnHand = 100,
                            ReOrderLevel = 100,
                            Schedule = "6",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 14,
                            CurrentPrice = 125,
                            DosageFormID = 5,
                            MedicationName = "DermaClear",
                            QuantityOnHand = 200,
                            ReOrderLevel = 100,
                            Schedule = "6",
                            SupplierID = 2
                        },
                        new
                        {
                            MedcationID = 15,
                            CurrentPrice = 190,
                            DosageFormID = 2,
                            MedicationName = "OsteoPrime",
                            QuantityOnHand = 400,
                            ReOrderLevel = 100,
                            Schedule = "6",
                            SupplierID = 2
                        });
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Medication_Ingredient", b =>
                {
                    b.Property<int>("Medication_IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Medication_IngredientID"));

                    b.Property<int>("Active_IngredientID")
                        .HasColumnType("int");

                    b.Property<int>("MedicationID")
                        .HasColumnType("int");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Medication_IngredientID");

                    b.HasIndex("Active_IngredientID");

                    b.HasIndex("MedicationID");

                    b.ToTable("Medication_Ingredients");

                    b.HasData(
                        new
                        {
                            Medication_IngredientID = 1,
                            Active_IngredientID = 6,
                            MedicationID = 1,
                            Strength = "18mg"
                        },
                        new
                        {
                            Medication_IngredientID = 2,
                            Active_IngredientID = 2,
                            MedicationID = 2,
                            Strength = "2mg"
                        },
                        new
                        {
                            Medication_IngredientID = 3,
                            Active_IngredientID = 3,
                            MedicationID = 2,
                            Strength = "50mg"
                        },
                        new
                        {
                            Medication_IngredientID = 4,
                            Active_IngredientID = 4,
                            MedicationID = 3,
                            Strength = "325mg"
                        },
                        new
                        {
                            Medication_IngredientID = 5,
                            Active_IngredientID = 5,
                            MedicationID = 3,
                            Strength = "453.6g"
                        },
                        new
                        {
                            Medication_IngredientID = 6,
                            Active_IngredientID = 1,
                            MedicationID = 4,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 7,
                            Active_IngredientID = 7,
                            MedicationID = 5,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 8,
                            Active_IngredientID = 8,
                            MedicationID = 5,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 9,
                            Active_IngredientID = 9,
                            MedicationID = 6,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 10,
                            Active_IngredientID = 10,
                            MedicationID = 6,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 11,
                            Active_IngredientID = 11,
                            MedicationID = 7,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 12,
                            Active_IngredientID = 12,
                            MedicationID = 8,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 13,
                            Active_IngredientID = 13,
                            MedicationID = 9,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 14,
                            Active_IngredientID = 14,
                            MedicationID = 9,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 15,
                            Active_IngredientID = 15,
                            MedicationID = 10,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 16,
                            Active_IngredientID = 16,
                            MedicationID = 10,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 17,
                            Active_IngredientID = 13,
                            MedicationID = 11,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 18,
                            Active_IngredientID = 6,
                            MedicationID = 11,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 19,
                            Active_IngredientID = 4,
                            MedicationID = 12,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 20,
                            Active_IngredientID = 7,
                            MedicationID = 13,
                            Strength = "Standard"
                        },
                        new
                        {
                            Medication_IngredientID = 21,
                            Active_IngredientID = 9,
                            MedicationID = 14,
                            Strength = "20mg"
                        },
                        new
                        {
                            Medication_IngredientID = 22,
                            Active_IngredientID = 13,
                            MedicationID = 15,
                            Strength = "20mg"
                        });
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.NewScript", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionID"));

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DispenseUponApproval")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Script")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionID");

                    b.ToTable("NewScripts");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PharmacistID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalDue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VAT")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PharmacistID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.OrderLine", b =>
                {
                    b.Property<int>("OrderLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLineID"));

                    b.Property<int>("ItemPrice")
                        .HasColumnType("int");

                    b.Property<int>("MedicationID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ScriptLineID")
                        .HasColumnType("int");

                    b.HasKey("OrderLineID");

                    b.HasIndex("MedicationID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ScriptLineID");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Pharmacist", b =>
                {
                    b.Property<int>("PharmacistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmacistID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HealthCouncilRegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PharmacistID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Pharmacy", b =>
                {
                    b.Property<int>("PharmacyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmacyID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCouncilRegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PharmacistID")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyManagerID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PharmacyID");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.PharmacyManager", b =>
                {
                    b.Property<int>("PharmacyManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmacyManagerID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HealthCouncilRegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PharmacyManagerID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("PharmacyManagers");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.PresScriptLine", b =>
                {
                    b.Property<int>("ScriptLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScriptLineID"));

                    b.Property<string>("DispenseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationID")
                        .HasColumnType("int");

                    b.Property<int?>("NewScriptPrescriptionID")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Repeats")
                        .HasColumnType("int");

                    b.Property<int>("RepeatsLeft")
                        .HasColumnType("int");

                    b.HasKey("ScriptLineID");

                    b.HasIndex("MedicationID");

                    b.HasIndex("NewScriptPrescriptionID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("PresScriptLines");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DispenseUponApproval")
                        .HasColumnType("bit");

                    b.Property<int?>("DoctorID")
                        .HasColumnType("int");

                    b.Property<byte[]>("Script")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("DoctorID");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.ScriptLine", b =>
                {
                    b.Property<int>("ScriptLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScriptLineID"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationID")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Repeats")
                        .HasColumnType("int");

                    b.Property<int>("RepeatsLeft")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScriptLineID");

                    b.HasIndex("MedicationID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("ScriptLines");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.StockOrder", b =>
                {
                    b.Property<int>("StockOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockOrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("StockOrderID");

                    b.ToTable("StockOrders");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.StockOrderDetail", b =>
                {
                    b.Property<int>("StockOrderDetail_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockOrderDetail_ID"));

                    b.Property<int>("MedicationID")
                        .HasColumnType("int");

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("int");

                    b.Property<int>("StockOrderID")
                        .HasColumnType("int");

                    b.HasKey("StockOrderDetail_ID");

                    b.ToTable("StockOrderDetails");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            ContactName = "Davie",
                            ContactSurname = "Jones",
                            EmailAddress = "davie@example.com",
                            SupplierName = "NovaCure"
                        },
                        new
                        {
                            SupplierID = 2,
                            ContactName = "Nicky",
                            ContactSurname = "Mostert",
                            EmailAddress = "nmostert@mandela.ac.za",
                            SupplierName = "HelixMed"
                        },
                        new
                        {
                            SupplierID = 3,
                            ContactName = "Matimu",
                            ContactSurname = "Vuqa",
                            EmailAddress = "matimu@example.com",
                            SupplierName = "VitaGenix"
                        },
                        new
                        {
                            SupplierID = 4,
                            ContactName = "Lulu",
                            ContactSurname = "Ndhambi",
                            EmailAddress = "lulu@example.com",
                            SupplierName = "Apex Biomed"
                        },
                        new
                        {
                            SupplierID = 5,
                            ContactName = "Pharmacy Manager Group Member Name",
                            ContactSurname = "Pharmacy Manager Group Member Surname",
                            EmailAddress = "Pharmacy Manager Group Member E-mail",
                            SupplierName = "CuraNova"
                        });
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.UnprocessedScripts", b =>
                {
                    b.Property<int>("UnprocessedScriptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnprocessedScriptID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dispense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnprocessedScriptID");

                    b.ToTable("UnprocessedScripts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int?>("Active_IngredientID")
                        .HasColumnType("int");

                    b.Property<string>("CellphoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Customer", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Custormer_Allergy", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.Active_Ingredient", "Active_Ingredient")
                        .WithMany()
                        .HasForeignKey("Active_IngredientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.Customer", "Customer")
                        .WithMany("CustomerAllergies")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Active_Ingredient");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Medication", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.DosageForm", "DosageForm")
                        .WithMany()
                        .HasForeignKey("DosageFormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DosageForm");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Medication_Ingredient", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.Active_Ingredient", "Active_Ingredients")
                        .WithMany()
                        .HasForeignKey("Active_IngredientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.Medication", "Medications")
                        .WithMany("Medication_Ingredients")
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Active_Ingredients");

                    b.Navigation("Medications");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Order", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.Pharmacist", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistID");

                    b.Navigation("Customer");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.OrderLine", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.Medication", "Medications")
                        .WithMany()
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.ScriptLine", "ScriptLine")
                        .WithMany()
                        .HasForeignKey("ScriptLineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medications");

                    b.Navigation("Order");

                    b.Navigation("ScriptLine");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Pharmacist", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.PharmacyManager", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.PresScriptLine", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.Medication", "Medications")
                        .WithMany()
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.NewScript", null)
                        .WithMany("scriptLines")
                        .HasForeignKey("NewScriptPrescriptionID");

                    b.HasOne("IbhayiPharmacy.Models.Prescription", "Prescriptions")
                        .WithMany()
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medications");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Prescription", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.Doctor", "Doctors")
                        .WithMany()
                        .HasForeignKey("DoctorID");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.ScriptLine", b =>
                {
                    b.HasOne("IbhayiPharmacy.Models.Medication", "Medications")
                        .WithMany()
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IbhayiPharmacy.Models.Prescription", "Prescriptions")
                        .WithMany("scriptLines")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medications");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Customer", b =>
                {
                    b.Navigation("CustomerAllergies");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Medication", b =>
                {
                    b.Navigation("Medication_Ingredients");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.NewScript", b =>
                {
                    b.Navigation("scriptLines");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("IbhayiPharmacy.Models.Prescription", b =>
                {
                    b.Navigation("scriptLines");
                });
#pragma warning restore 612, 618
        }
    }
}
